NAME        =    libft.a

IDIR        =    libft.h

SRCS		=	ft_atoi.c \
					ft_isalnum.c \
					ft_isalpha.c \
					ft_isascii.c \
					ft_isprint.c \
					ft_isdigit.c \
					ft_memcmp.c \
					ft_strncmp.c \
					ft_toupper.c \
					ft_tolower.c \
					ft_bzero.c \
					ft_putchar_fd.c \
					ft_putendl_fd.c \
					ft_putnbr_fd.c \
					ft_putstr_fd.c \
					ft_striteri.c \
					ft_itoa.c \
					ft_split.c \
					ft_straddchar.c \
					ft_strchr.c \
					ft_strdup.c \
					ft_strnstr.c \
					ft_strrchr.c \
					ft_strtrim.c \
					ft_substr.c \
					ft_strlcat.c \
					ft_strlcpy.c \
					ft_strlen.c \
					ft_memchr.c \
					ft_memcpy.c \
					ft_memmove.c \
					ft_memset.c \
					ft_calloc.c \
					ft_strjoin.c \
					ft_strmapi.c \
					my_ft_strncpy.c \

BONUS		=	ft_lstsize.c \
					ft_lstadd_back.c \
					ft_lstadd_front.c \
					ft_lstdelone.c \
					ft_lstiter.c \
					ft_lstlast.c \
					ft_lstmap.c \
					ft_lstnew.c \
					ft_lstclear.c \


OBJS		=	$(SRCS:.c=.o)
OBJS_BONUS	=	$(BONUS:.c=.o)
CC			=	cc
CFLAGS		=	-Wall -Wextra -Werror -c
RM			=	rm -f
NORM		=	norminette *.h && norminette *.c 

all			:	$(NAME)

$(NAME)		:	$(OBJS)
	ar rcs $(NAME) $(OBJS)

bonus		:	$(OBJS) $(OBJS_BONUS)
	ar rcs $(NAME) $(OBJS) $(OBJS_BONUS)

n			:
	$(NORM)

clean		:
	$(RM) $(OBJS) $(OBJS_BONUS)

fclean		:	clean
	$(RM) $(NAME)

re			:	fclean all

.PHONY:		all clean fclean re bonus
